GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "My FSO Blog",
    "author": "Tero Kilpeläinen",
    "url": "https://coolblogs.dev/5",
    "likes": 30
}