GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NTNhNzQ5YjI0ZjAxNzcxODMyODdlMWMiLCJpYXQiOjE2OTgzOTkyNzcsImV4cCI6MTY5ODQwMjg3N30.nAPUo7w2fyOs_ozXj0DazSzjROW1ZbdgOqLoF3uR4hA

{
    "title": "The blog to delete",
    "url": "https://coolblogs.dev/12",
    "likes": 666
}
###
GET http://localhost:3003/api/users/ HTTP/1.1
###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "test <>",
    "name": "Test User",
    "password": "salasanA|123"
}
###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "testuser",
    "password": "salasanA|123"
}
###
DELETE http://localhost:3003/api/blogs/653b8aa85f31ef3736b3d021 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NTNhNzQ5YjI0ZjAxNzcxODMyODdlMWMiLCJpYXQiOjE2OTgzOTkyNzcsImV4cCI6MTY5ODQwMjg3N30.nAPUo7w2fyOs_ozXj0DazSzjROW1ZbdgOqLoF3uR4hA