GET http://localhost:3003/api/blogs/ HTTP/1.1
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "My second Blog!",
    "author": "Tero Kilpeläinen",
    "url": "https://coolblogs.dev/2",
    "likes": 4
}